services:
  react:
    build:
      context: .
      dockerfile: servicios/frontend/Dockerfile
    ports:
      - "5173:5173"
    working_dir: /app
    command: npm run dev
    stdin_open: true
    tty: true
    
  fastapi:
    build:
      context: .
      dockerfile: servicios/backend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

  database:
    image: mariadb:10.11
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
    ports:
      - "3360:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/anki.sql

volumes:
  db_data: